include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true

analyzer:
  errors:
    use_full_hex_values_for_flutter_colors: ignore
  plugins:
    - custom_lint
