name: yominexus
description: "Yominexus is an all-in-one content aggregator inspired by Tachiyomi, Mihon, Aniyomi, and QuickNovel. \n  It provides a seamless reading experience for manga, novels, and anime tracking, allowing users \n  to explore, organize, and enjoy their favorite content from multiple sources in one app. \n  With a customizable interface, offline reading support, and extensive plugin options, \n  Yominexus is your ultimate companion for endless entertainment."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
