name: yominexus
description: "A free and open source cross-platform application that is inspired by Tachiyomi, Aniyomi and QuickNovel"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
